#!/usr/bin/env php
<?php

declare(strict_types=1);

defined('YII_DEBUG') or define('YII_DEBUG', (bool) (getenv('YII_DEBUG') ?: false));
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV') ?: 'prod');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

exit((new yii\console\Application(require __DIR__ . '/config/console.php'))->run());
